// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrsadhufnvpayrehnjoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyc2FkaHVmbnZwYXlyZWhuam9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTAyNDksImV4cCI6MjA2OTA2NjI0OX0.U6HNxXRTLehYcDY3x3O0MN11k_Hwg054XMUwE8MZ7mM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});